---
apiVersion: batch/v1
kind: Job
metadata:
  name: cordinator-job
  namespace: wazuh
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: cordinator-pod
    spec:
      priorityClassName: system-cluster-critical
  containers:
  - name: cordinator
    image: python:3.6-alpine3.10
    command: ["/bin/ash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
  serviceAccountName: cordinator