---
apiVersion: batch/v1
kind: Job
metadata:
  name: cordinator-job
  namespace: wazuh
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: cordinator-pod
    spec:
      priorityClassName: system-cluster-critical
      containers:
        - name: cordinator
          image: us.gcr.io/k8s-artifacts-prod/descheduler/descheduler:v0.10.0
          volumeMounts:
          - mountPath: /policy-dir
            name: policy-volume
          command:
            - "/bin/descheduler"
          args:
            - "--policy-config-file"
            - "/policy-dir/policy.yaml"
            - "--v"
            - "3"
      restartPolicy: "Never"
      serviceAccountName: cordinator